### ISSUE TITLE
Pipeline fails to upload results to Argus

### ISSUE THREAD

**Issue by soyacz** [scylladb/gocql-driver-matrix#13]
from e.g.:https://jenkins.scylladb.com/job/scylla-master/job/driver-tests/job/gocql-driver-matrix-test/55/execution/node/372/log/:
```
03:51:17  INFO:__main__:Uploading driver matrix results...
03:51:18  Traceback (most recent call last):
03:51:18    File "/app/entry.py", line 52, in <module>
03:51:18      main()
03:51:18    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
03:51:18      return self.main(*args, **kwargs)
03:51:18    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
03:51:18      rv = self.invoke(ctx)
03:51:18    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
03:51:18      return ctx.invoke(self.callback, **ctx.params)
03:51:18    File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
03:51:18      return __callback(*args, **kwargs)
03:51:18    File "/app/entry.py", line 42, in main
03:51:18      client.submit(
03:51:18    File "/usr/local/lib/python3.10/site-packages/argus/client/driver_matrix_tests/client.py", line 200, in submit
03:51:18      self.submit_driver_matrix_run(job_name=build_id, job_url=build_url, test_environment=env, results=results)
03:51:18    File "/usr/local/lib/python3.10/site-packages/argus/client/driver_matrix_tests/client.py", line 212, in submit_driver_matrix_run
03:51:18      self.check_response(response)
03:51:18    File "/usr/local/lib/python3.10/site-packages/argus/client/base.py", line 64, in check_response
03:51:18      raise ArgusClientError(
03:51:18  argus.client.base.ArgusClientError: ('API Error encountered using endpoint: POST /api/v1/client/testrun/driver-matrix-tests/submit', "Invalid isoformat string: '2023-10-12T01:36:53Z'")
```

**Comment by roydahan** [comment]
@k0machi is it still relevant?

**Comment by fruch** [comment]
> @k0machi is it still relevant?
> 

It's fixed
